//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace AgroVentas.Droid.AgroVentasWebServ {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AgroVentasWSSoap", Namespace="http://trujillo-lia.org")]
    public partial class AgroVentasWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback LoginAccionOperationCompleted;
        
        private System.Threading.SendOrPostCallback ProcesarDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback UsuarioDataBDOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerPedidosListaOperationCompleted;
        
        private System.Threading.SendOrPostCallback RecuperarPasswordOperationCompleted;
        
        private System.Threading.SendOrPostCallback CrearClienteFichaPDFOperationCompleted;
        
        private System.Threading.SendOrPostCallback CrearOrdenPedidoPDFOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerOrdenPedidoDocOperationCompleted;
        
        private System.Threading.SendOrPostCallback CrearCotizacionPDFOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerManualesUrlOperationCompleted;
        
        private System.Threading.SendOrPostCallback AsignarOPRepartidorOperationCompleted;
        
        private System.Threading.SendOrPostCallback CambiarEstatusOPOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerIDRepartidorOPOperationCompleted;
        
        private System.Threading.SendOrPostCallback EntregarReporteOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AgroVentasWS() {
            this.Url = "http://www.agroventas2236.com/AgroVentasWS.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event LoginAccionCompletedEventHandler LoginAccionCompleted;
        
        /// <remarks/>
        public event ProcesarDataCompletedEventHandler ProcesarDataCompleted;
        
        /// <remarks/>
        public event UsuarioDataBDCompletedEventHandler UsuarioDataBDCompleted;
        
        /// <remarks/>
        public event ObtenerPedidosListaCompletedEventHandler ObtenerPedidosListaCompleted;
        
        /// <remarks/>
        public event RecuperarPasswordCompletedEventHandler RecuperarPasswordCompleted;
        
        /// <remarks/>
        public event CrearClienteFichaPDFCompletedEventHandler CrearClienteFichaPDFCompleted;
        
        /// <remarks/>
        public event CrearOrdenPedidoPDFCompletedEventHandler CrearOrdenPedidoPDFCompleted;
        
        /// <remarks/>
        public event ObtenerOrdenPedidoDocCompletedEventHandler ObtenerOrdenPedidoDocCompleted;
        
        /// <remarks/>
        public event CrearCotizacionPDFCompletedEventHandler CrearCotizacionPDFCompleted;
        
        /// <remarks/>
        public event ObtenerManualesUrlCompletedEventHandler ObtenerManualesUrlCompleted;
        
        /// <remarks/>
        public event AsignarOPRepartidorCompletedEventHandler AsignarOPRepartidorCompleted;
        
        /// <remarks/>
        public event CambiarEstatusOPCompletedEventHandler CambiarEstatusOPCompleted;
        
        /// <remarks/>
        public event ObtenerIDRepartidorOPCompletedEventHandler ObtenerIDRepartidorOPCompleted;
        
        /// <remarks/>
        public event EntregarReporteCompletedEventHandler EntregarReporteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://trujillo-lia.org/LoginAccion", RequestNamespace="http://trujillo-lia.org", ResponseNamespace="http://trujillo-lia.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string LoginAccion(string logininfo) {
            object[] results = this.Invoke("LoginAccion", new object[] {
                        logininfo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LoginAccionAsync(string logininfo) {
            this.LoginAccionAsync(logininfo, null);
        }
        
        /// <remarks/>
        public void LoginAccionAsync(string logininfo, object userState) {
            if ((this.LoginAccionOperationCompleted == null)) {
                this.LoginAccionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginAccionOperationCompleted);
            }
            this.InvokeAsync("LoginAccion", new object[] {
                        logininfo}, this.LoginAccionOperationCompleted, userState);
        }
        
        private void OnLoginAccionOperationCompleted(object arg) {
            if ((this.LoginAccionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginAccionCompleted(this, new LoginAccionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://trujillo-lia.org/ProcesarData", RequestNamespace="http://trujillo-lia.org", ResponseNamespace="http://trujillo-lia.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ProcesarData(string dataapp, int idusuario) {
            object[] results = this.Invoke("ProcesarData", new object[] {
                        dataapp,
                        idusuario});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ProcesarDataAsync(string dataapp, int idusuario) {
            this.ProcesarDataAsync(dataapp, idusuario, null);
        }
        
        /// <remarks/>
        public void ProcesarDataAsync(string dataapp, int idusuario, object userState) {
            if ((this.ProcesarDataOperationCompleted == null)) {
                this.ProcesarDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProcesarDataOperationCompleted);
            }
            this.InvokeAsync("ProcesarData", new object[] {
                        dataapp,
                        idusuario}, this.ProcesarDataOperationCompleted, userState);
        }
        
        private void OnProcesarDataOperationCompleted(object arg) {
            if ((this.ProcesarDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProcesarDataCompleted(this, new ProcesarDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://trujillo-lia.org/UsuarioDataBD", RequestNamespace="http://trujillo-lia.org", ResponseNamespace="http://trujillo-lia.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UsuarioDataBD(int idusuario) {
            object[] results = this.Invoke("UsuarioDataBD", new object[] {
                        idusuario});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UsuarioDataBDAsync(int idusuario) {
            this.UsuarioDataBDAsync(idusuario, null);
        }
        
        /// <remarks/>
        public void UsuarioDataBDAsync(int idusuario, object userState) {
            if ((this.UsuarioDataBDOperationCompleted == null)) {
                this.UsuarioDataBDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUsuarioDataBDOperationCompleted);
            }
            this.InvokeAsync("UsuarioDataBD", new object[] {
                        idusuario}, this.UsuarioDataBDOperationCompleted, userState);
        }
        
        private void OnUsuarioDataBDOperationCompleted(object arg) {
            if ((this.UsuarioDataBDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UsuarioDataBDCompleted(this, new UsuarioDataBDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://trujillo-lia.org/ObtenerPedidosLista", RequestNamespace="http://trujillo-lia.org", ResponseNamespace="http://trujillo-lia.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ObtenerPedidosLista(string pedidoinfo) {
            object[] results = this.Invoke("ObtenerPedidosLista", new object[] {
                        pedidoinfo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerPedidosListaAsync(string pedidoinfo) {
            this.ObtenerPedidosListaAsync(pedidoinfo, null);
        }
        
        /// <remarks/>
        public void ObtenerPedidosListaAsync(string pedidoinfo, object userState) {
            if ((this.ObtenerPedidosListaOperationCompleted == null)) {
                this.ObtenerPedidosListaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerPedidosListaOperationCompleted);
            }
            this.InvokeAsync("ObtenerPedidosLista", new object[] {
                        pedidoinfo}, this.ObtenerPedidosListaOperationCompleted, userState);
        }
        
        private void OnObtenerPedidosListaOperationCompleted(object arg) {
            if ((this.ObtenerPedidosListaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerPedidosListaCompleted(this, new ObtenerPedidosListaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://trujillo-lia.org/RecuperarPassword", RequestNamespace="http://trujillo-lia.org", ResponseNamespace="http://trujillo-lia.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RecuperarPassword(string usuarioparams) {
            object[] results = this.Invoke("RecuperarPassword", new object[] {
                        usuarioparams});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RecuperarPasswordAsync(string usuarioparams) {
            this.RecuperarPasswordAsync(usuarioparams, null);
        }
        
        /// <remarks/>
        public void RecuperarPasswordAsync(string usuarioparams, object userState) {
            if ((this.RecuperarPasswordOperationCompleted == null)) {
                this.RecuperarPasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecuperarPasswordOperationCompleted);
            }
            this.InvokeAsync("RecuperarPassword", new object[] {
                        usuarioparams}, this.RecuperarPasswordOperationCompleted, userState);
        }
        
        private void OnRecuperarPasswordOperationCompleted(object arg) {
            if ((this.RecuperarPasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecuperarPasswordCompleted(this, new RecuperarPasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://trujillo-lia.org/CrearClienteFichaPDF", RequestNamespace="http://trujillo-lia.org", ResponseNamespace="http://trujillo-lia.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CrearClienteFichaPDF(string clientesinfo, string correos, int idusuario) {
            object[] results = this.Invoke("CrearClienteFichaPDF", new object[] {
                        clientesinfo,
                        correos,
                        idusuario});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CrearClienteFichaPDFAsync(string clientesinfo, string correos, int idusuario) {
            this.CrearClienteFichaPDFAsync(clientesinfo, correos, idusuario, null);
        }
        
        /// <remarks/>
        public void CrearClienteFichaPDFAsync(string clientesinfo, string correos, int idusuario, object userState) {
            if ((this.CrearClienteFichaPDFOperationCompleted == null)) {
                this.CrearClienteFichaPDFOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCrearClienteFichaPDFOperationCompleted);
            }
            this.InvokeAsync("CrearClienteFichaPDF", new object[] {
                        clientesinfo,
                        correos,
                        idusuario}, this.CrearClienteFichaPDFOperationCompleted, userState);
        }
        
        private void OnCrearClienteFichaPDFOperationCompleted(object arg) {
            if ((this.CrearClienteFichaPDFCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CrearClienteFichaPDFCompleted(this, new CrearClienteFichaPDFCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://trujillo-lia.org/CrearOrdenPedidoPDF", RequestNamespace="http://trujillo-lia.org", ResponseNamespace="http://trujillo-lia.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CrearOrdenPedidoPDF(string pedidoinfo, int idusuario) {
            object[] results = this.Invoke("CrearOrdenPedidoPDF", new object[] {
                        pedidoinfo,
                        idusuario});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CrearOrdenPedidoPDFAsync(string pedidoinfo, int idusuario) {
            this.CrearOrdenPedidoPDFAsync(pedidoinfo, idusuario, null);
        }
        
        /// <remarks/>
        public void CrearOrdenPedidoPDFAsync(string pedidoinfo, int idusuario, object userState) {
            if ((this.CrearOrdenPedidoPDFOperationCompleted == null)) {
                this.CrearOrdenPedidoPDFOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCrearOrdenPedidoPDFOperationCompleted);
            }
            this.InvokeAsync("CrearOrdenPedidoPDF", new object[] {
                        pedidoinfo,
                        idusuario}, this.CrearOrdenPedidoPDFOperationCompleted, userState);
        }
        
        private void OnCrearOrdenPedidoPDFOperationCompleted(object arg) {
            if ((this.CrearOrdenPedidoPDFCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CrearOrdenPedidoPDFCompleted(this, new CrearOrdenPedidoPDFCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://trujillo-lia.org/ObtenerOrdenPedidoDoc", RequestNamespace="http://trujillo-lia.org", ResponseNamespace="http://trujillo-lia.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ObtenerOrdenPedidoDoc(int idusuario, string tipodocumento, string folioadicional) {
            object[] results = this.Invoke("ObtenerOrdenPedidoDoc", new object[] {
                        idusuario,
                        tipodocumento,
                        folioadicional});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerOrdenPedidoDocAsync(int idusuario, string tipodocumento, string folioadicional) {
            this.ObtenerOrdenPedidoDocAsync(idusuario, tipodocumento, folioadicional, null);
        }
        
        /// <remarks/>
        public void ObtenerOrdenPedidoDocAsync(int idusuario, string tipodocumento, string folioadicional, object userState) {
            if ((this.ObtenerOrdenPedidoDocOperationCompleted == null)) {
                this.ObtenerOrdenPedidoDocOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerOrdenPedidoDocOperationCompleted);
            }
            this.InvokeAsync("ObtenerOrdenPedidoDoc", new object[] {
                        idusuario,
                        tipodocumento,
                        folioadicional}, this.ObtenerOrdenPedidoDocOperationCompleted, userState);
        }
        
        private void OnObtenerOrdenPedidoDocOperationCompleted(object arg) {
            if ((this.ObtenerOrdenPedidoDocCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerOrdenPedidoDocCompleted(this, new ObtenerOrdenPedidoDocCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://trujillo-lia.org/CrearCotizacionPDF", RequestNamespace="http://trujillo-lia.org", ResponseNamespace="http://trujillo-lia.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CrearCotizacionPDF(int idusuario, string cotizaciondata) {
            object[] results = this.Invoke("CrearCotizacionPDF", new object[] {
                        idusuario,
                        cotizaciondata});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CrearCotizacionPDFAsync(int idusuario, string cotizaciondata) {
            this.CrearCotizacionPDFAsync(idusuario, cotizaciondata, null);
        }
        
        /// <remarks/>
        public void CrearCotizacionPDFAsync(int idusuario, string cotizaciondata, object userState) {
            if ((this.CrearCotizacionPDFOperationCompleted == null)) {
                this.CrearCotizacionPDFOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCrearCotizacionPDFOperationCompleted);
            }
            this.InvokeAsync("CrearCotizacionPDF", new object[] {
                        idusuario,
                        cotizaciondata}, this.CrearCotizacionPDFOperationCompleted, userState);
        }
        
        private void OnCrearCotizacionPDFOperationCompleted(object arg) {
            if ((this.CrearCotizacionPDFCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CrearCotizacionPDFCompleted(this, new CrearCotizacionPDFCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://trujillo-lia.org/ObtenerManualesUrl", RequestNamespace="http://trujillo-lia.org", ResponseNamespace="http://trujillo-lia.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ObtenerManualesUrl() {
            object[] results = this.Invoke("ObtenerManualesUrl", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerManualesUrlAsync() {
            this.ObtenerManualesUrlAsync(null);
        }
        
        /// <remarks/>
        public void ObtenerManualesUrlAsync(object userState) {
            if ((this.ObtenerManualesUrlOperationCompleted == null)) {
                this.ObtenerManualesUrlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerManualesUrlOperationCompleted);
            }
            this.InvokeAsync("ObtenerManualesUrl", new object[0], this.ObtenerManualesUrlOperationCompleted, userState);
        }
        
        private void OnObtenerManualesUrlOperationCompleted(object arg) {
            if ((this.ObtenerManualesUrlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerManualesUrlCompleted(this, new ObtenerManualesUrlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://trujillo-lia.org/AsignarOPRepartidor", RequestNamespace="http://trujillo-lia.org", ResponseNamespace="http://trujillo-lia.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AsignarOPRepartidor(int idusuario, int idordenpedido, string repartidor) {
            object[] results = this.Invoke("AsignarOPRepartidor", new object[] {
                        idusuario,
                        idordenpedido,
                        repartidor});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AsignarOPRepartidorAsync(int idusuario, int idordenpedido, string repartidor) {
            this.AsignarOPRepartidorAsync(idusuario, idordenpedido, repartidor, null);
        }
        
        /// <remarks/>
        public void AsignarOPRepartidorAsync(int idusuario, int idordenpedido, string repartidor, object userState) {
            if ((this.AsignarOPRepartidorOperationCompleted == null)) {
                this.AsignarOPRepartidorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAsignarOPRepartidorOperationCompleted);
            }
            this.InvokeAsync("AsignarOPRepartidor", new object[] {
                        idusuario,
                        idordenpedido,
                        repartidor}, this.AsignarOPRepartidorOperationCompleted, userState);
        }
        
        private void OnAsignarOPRepartidorOperationCompleted(object arg) {
            if ((this.AsignarOPRepartidorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AsignarOPRepartidorCompleted(this, new AsignarOPRepartidorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://trujillo-lia.org/CambiarEstatusOP", RequestNamespace="http://trujillo-lia.org", ResponseNamespace="http://trujillo-lia.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CambiarEstatusOP(int idusuario, int idordenpedido, int estatus) {
            object[] results = this.Invoke("CambiarEstatusOP", new object[] {
                        idusuario,
                        idordenpedido,
                        estatus});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CambiarEstatusOPAsync(int idusuario, int idordenpedido, int estatus) {
            this.CambiarEstatusOPAsync(idusuario, idordenpedido, estatus, null);
        }
        
        /// <remarks/>
        public void CambiarEstatusOPAsync(int idusuario, int idordenpedido, int estatus, object userState) {
            if ((this.CambiarEstatusOPOperationCompleted == null)) {
                this.CambiarEstatusOPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCambiarEstatusOPOperationCompleted);
            }
            this.InvokeAsync("CambiarEstatusOP", new object[] {
                        idusuario,
                        idordenpedido,
                        estatus}, this.CambiarEstatusOPOperationCompleted, userState);
        }
        
        private void OnCambiarEstatusOPOperationCompleted(object arg) {
            if ((this.CambiarEstatusOPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CambiarEstatusOPCompleted(this, new CambiarEstatusOPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://trujillo-lia.org/ObtenerIDRepartidorOP", RequestNamespace="http://trujillo-lia.org", ResponseNamespace="http://trujillo-lia.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ObtenerIDRepartidorOP(int idusuario, int idordenpedido) {
            object[] results = this.Invoke("ObtenerIDRepartidorOP", new object[] {
                        idusuario,
                        idordenpedido});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerIDRepartidorOPAsync(int idusuario, int idordenpedido) {
            this.ObtenerIDRepartidorOPAsync(idusuario, idordenpedido, null);
        }
        
        /// <remarks/>
        public void ObtenerIDRepartidorOPAsync(int idusuario, int idordenpedido, object userState) {
            if ((this.ObtenerIDRepartidorOPOperationCompleted == null)) {
                this.ObtenerIDRepartidorOPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerIDRepartidorOPOperationCompleted);
            }
            this.InvokeAsync("ObtenerIDRepartidorOP", new object[] {
                        idusuario,
                        idordenpedido}, this.ObtenerIDRepartidorOPOperationCompleted, userState);
        }
        
        private void OnObtenerIDRepartidorOPOperationCompleted(object arg) {
            if ((this.ObtenerIDRepartidorOPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerIDRepartidorOPCompleted(this, new ObtenerIDRepartidorOPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://trujillo-lia.org/EntregarReporte", RequestNamespace="http://trujillo-lia.org", ResponseNamespace="http://trujillo-lia.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EntregarReporte(int idusuario, string dataestructura, int reporte) {
            object[] results = this.Invoke("EntregarReporte", new object[] {
                        idusuario,
                        dataestructura,
                        reporte});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EntregarReporteAsync(int idusuario, string dataestructura, int reporte) {
            this.EntregarReporteAsync(idusuario, dataestructura, reporte, null);
        }
        
        /// <remarks/>
        public void EntregarReporteAsync(int idusuario, string dataestructura, int reporte, object userState) {
            if ((this.EntregarReporteOperationCompleted == null)) {
                this.EntregarReporteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEntregarReporteOperationCompleted);
            }
            this.InvokeAsync("EntregarReporte", new object[] {
                        idusuario,
                        dataestructura,
                        reporte}, this.EntregarReporteOperationCompleted, userState);
        }
        
        private void OnEntregarReporteOperationCompleted(object arg) {
            if ((this.EntregarReporteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EntregarReporteCompleted(this, new EntregarReporteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void LoginAccionCompletedEventHandler(object sender, LoginAccionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginAccionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginAccionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void ProcesarDataCompletedEventHandler(object sender, ProcesarDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProcesarDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProcesarDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void UsuarioDataBDCompletedEventHandler(object sender, UsuarioDataBDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UsuarioDataBDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UsuarioDataBDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void ObtenerPedidosListaCompletedEventHandler(object sender, ObtenerPedidosListaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerPedidosListaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerPedidosListaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void RecuperarPasswordCompletedEventHandler(object sender, RecuperarPasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecuperarPasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecuperarPasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void CrearClienteFichaPDFCompletedEventHandler(object sender, CrearClienteFichaPDFCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CrearClienteFichaPDFCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CrearClienteFichaPDFCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void CrearOrdenPedidoPDFCompletedEventHandler(object sender, CrearOrdenPedidoPDFCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CrearOrdenPedidoPDFCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CrearOrdenPedidoPDFCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void ObtenerOrdenPedidoDocCompletedEventHandler(object sender, ObtenerOrdenPedidoDocCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerOrdenPedidoDocCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerOrdenPedidoDocCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void CrearCotizacionPDFCompletedEventHandler(object sender, CrearCotizacionPDFCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CrearCotizacionPDFCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CrearCotizacionPDFCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void ObtenerManualesUrlCompletedEventHandler(object sender, ObtenerManualesUrlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerManualesUrlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerManualesUrlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void AsignarOPRepartidorCompletedEventHandler(object sender, AsignarOPRepartidorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AsignarOPRepartidorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AsignarOPRepartidorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void CambiarEstatusOPCompletedEventHandler(object sender, CambiarEstatusOPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CambiarEstatusOPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CambiarEstatusOPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void ObtenerIDRepartidorOPCompletedEventHandler(object sender, ObtenerIDRepartidorOPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerIDRepartidorOPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerIDRepartidorOPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void EntregarReporteCompletedEventHandler(object sender, EntregarReporteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EntregarReporteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EntregarReporteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591